[package]
name = "starknet_esign"
version = "0.1.0"
edition = "2023_01" # Using a simpler, well-tested Cairo edition

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.3.0"

[dev-dependencies]
cairo_test = "2.9.2"
